version: "2"
services:
  app:
    container_name: mysql_app
    build: app/.
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

