FROM mysql:5.7

RUN mkdir /tmp/scripts

RUN cd /tmp/scripts
RUN git clone https://github.com/monika412/mysql_docker_compose

RUN chmod +x /tmp/scripts/db/createdb.sh

ENTRYPOINT /bin/sh /tmp/scripts/db/createdb.sh
