FROM mysql:5.7

RUN mkdir /tmp/scripts

#RUN apk update \
#  && apk add curl bash binutils tar git

RUN cd /tmp/scripts

COPY createdb.sh /tmp/scripts/createdb.sh
#RUN git clone https://github.com/monika412/mysql_docker_compose

RUN chmod +x /tmp/scripts/createdb.sh

ENTRYPOINT /bin/sh /tmp/scripts/createdb.sh
